//NOTICE
export const CREATE_NOTICE = "CREATE_NOTICE"
export const CREATE_NOTICE_RED = "CREATE_NOTICE_RED"
export const GET_NOTICE = "GET_NOTICE"
export const GET_NOTICE_RED = "GET_NOTICE_RED"
export const UPDATE_NOTICE = "UPDATE_NOTICE"
export const UPDATE_NOTICE_RED = "UPDATE_NOTICE_RED"
export const DELETE_NOTICE = "DELETE_NOTICE"
export const DELETE_NOTICE_RED = "DELETE_NOTICE_RED"


//EVENTS
export const CREATE_EVENTS = "CREATE_EVENTS"
export const CREATE_EVENTS_RED = "CREATE_EVENTS_RED"
export const GET_EVENTS = "GET_EVENTS"
export const GET_EVENTS_RED = "GET_EVENTS_RED"
export const UPDATE_EVENTS = "UPDATE_EVENTS"
export const UPDATE_EVENTS_RED = "UPDATE_EVENTS_RED"
export const DELETE_EVENTS = "DELETE_EVENTS"
export const DELETE_EVENTS_RED = "DELETE_EVENTS_RED"

//COMPLAINT
export const CREATE_COMPLAINT = "CREATE_COMPLAINT"
export const CREATE_COMPLAINT_RED = "CREATE_COMPLAINT_RED"
export const GET_COMPLAINT = "GET_COMPLAINT"
export const GET_COMPLAINT_RED = "GET_COMPLAINT_RED"
export const UPDATE_COMPLAINT = "UPDATE_COMPLAINT"
export const UPDATE_COMPLAINT_RED = "UPDATE_COMPLAINT_RED"
export const DELETE_COMPLAINT = "DELETE_COMPLAINT"
export const DELETE_COMPLAINT_RED = "DELETE_COMPLAINT_RED"

//RESIDENT
export const CREATE_RESIDENT = "CREATE_RESIDENT"
export const CREATE_RESIDENT_RED = "CREATE_RESIDENT_RED"
export const GET_RESIDENT = "GET_RESIDENT"
export const GET_RESIDENT_RED = "GET_RESIDENT_RED"
export const UPDATE_RESIDENT = "UPDATE_RESIDENT"
export const UPDATE_RESIDENT_RED = "UPDATE_RESIDENT_RED"
export const DELETE_RESIDENT = "DELETE_RESIDENT"
export const DELETE_RESIDENT_RED = "DELETE_RESIDENT_RED"

//PRODUCT
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_RED = "GET_PRODUCT_RED"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED"

//FEATURE
export const CREATE_FEATURE = "CREATE_FEATURE"
export const CREATE_FEATURE_RED = "CREATE_FEATURE_RED"
export const GET_FEATURE = "GET_FEATURE"
export const GET_FEATURE_RED = "GET_FEATURE_RED"
export const UPDATE_FEATURE = "UPDATE_FEATURE"
export const UPDATE_FEATURE_RED = "UPDATE_FEATURE_RED"
export const DELETE_FEATURE = "DELETE_FEATURE"
export const DELETE_FEATURE_RED = "DELETE_FEATURE_RED"

//FAQ
export const CREATE_FAQ = "CREATE_FAQ"
export const CREATE_FAQ_RED = "CREATE_FAQ_RED"
export const GET_FAQ = "GET_FAQ"
export const GET_FAQ_RED = "GET_FAQ_RED"
export const UPDATE_FAQ = "UPDATE_FAQ"
export const UPDATE_FAQ_RED = "UPDATE_FAQ_RED"
export const DELETE_FAQ = "DELETE_FAQ"
export const DELETE_FAQ_RED = "DELETE_FAQ_RED"

//SETTING
export const CREATE_SETTING = "CREATE_SETTING"
export const CREATE_SETTING_RED = "CREATE_SETTING_RED"
export const GET_SETTING = "GET_SETTING"
export const GET_SETTING_RED = "GET_SETTING_RED"
export const UPDATE_SETTING = "UPDATE_SETTING"
export const UPDATE_SETTING_RED = "UPDATE_SETTING_RED"
export const DELETE_SETTING = "DELETE_SETTING"
export const DELETE_SETTING_RED = "DELETE_SETTING_RED"


//NEWSLETTER
export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER"
export const CREATE_NEWSLETTER_RED = "CREATE_NEWSLETTER_RED"
export const GET_NEWSLETTER = "GET_NEWSLETTER"
export const GET_NEWSLETTER_RED = "GET_NEWSLETTER_RED"
export const UPDATE_NEWSLETTER = "UPDATE_NEWSLETTER"
export const UPDATE_NEWSLETTER_RED = "UPDATE_NEWSLETTER_RED"
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_RED = "DELETE_NEWSLETTER_RED"

//CONTACT_US
export const CREATE_CONTACT_US = "CREATE_CONTACT_US"
export const CREATE_CONTACT_US_RED = "CREATE_CONTACT_US_RED"
export const GET_CONTACT_US = "GET_CONTACT_US"
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED"
export const UPDATE_CONTACT_US = "UPDATE_CONTACT_US"
export const UPDATE_CONTACT_US_RED = "UPDATE_CONTACT_US_RED"
export const DELETE_CONTACT_US = "DELETE_CONTACT_US"
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED"

//TESTIMONIAL
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED"
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"

//USER
export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_RED = "CREATE_USER_RED"
export const GET_USER = "GET_USER"
export const GET_USER_RED = "GET_USER_RED"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_RED = "UPDATE_USER_RED"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_RED = "DELETE_USER_RED"

